# 感知机（单神经元）

In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
X=np.array([[1,3,3],
            [1,4,3],
            [1,1,1],
            [1,0,2]
            ])

Y=np.array([[1],[1],[-1],[-1]])
W=2*(np.random.random([3,1])-0.5)
print(W)
lr=0.11
o=0
def update():
    global X,Y,W,lr
    o=np.sign(np.dot(X,W))
    W_C=lr*(X.T.dot(Y-o)/int(X.shape[0]))
    W=W+W_C



[[ 0.48284004]
 [ 0.73487726]
 [-0.49615639]]


In [14]:
for i in range(100):
    update()
    print(W)
    print(i)
    O=np.sign(np.dot(X,W))
    if (O==Y).all():
        print('Finished')
        print('epoch',i)
        break


[[ 0.42784004]
 [ 0.67987726]
 [-0.55115639]]
0
[[ 0.37284004]
 [ 0.62487726]
 [-0.60615639]]
1
[[ 0.31784004]
 [ 0.56987726]
 [-0.66115639]]
2
[[ 0.26284004]
 [ 0.51487726]
 [-0.71615639]]
3
[[ 0.26284004]
 [ 0.62487726]
 [-0.60615639]]
4
[[ 0.20784004]
 [ 0.56987726]
 [-0.66115639]]
5
[[ 0.20784004]
 [ 0.67987726]
 [-0.55115639]]
6
[[ 0.15284004]
 [ 0.62487726]
 [-0.60615639]]
7
[[ 0.09784004]
 [ 0.56987726]
 [-0.66115639]]
8
[[ 0.09784004]
 [ 0.67987726]
 [-0.55115639]]
9
[[ 0.04284004]
 [ 0.62487726]
 [-0.60615639]]
10
[[-0.01215996]
 [ 0.56987726]
 [-0.66115639]]
11
[[ 0.04284004]
 [ 0.73487726]
 [-0.49615639]]
12
[[-0.01215996]
 [ 0.67987726]
 [-0.55115639]]
13
[[-0.06715996]
 [ 0.62487726]
 [-0.60615639]]
14
[[-0.01215996]
 [ 0.78987726]
 [-0.44115639]]
15
[[-0.06715996]
 [ 0.73487726]
 [-0.49615639]]
16
[[-0.12215996]
 [ 0.67987726]
 [-0.55115639]]
17
[[-0.17715996]
 [ 0.62487726]
 [-0.60615639]]
18
[[-0.12215996]
 [ 0.78987726]
 [-0.44115639]]
19
[[-0.17715996]
 [ 0.73487726]
